# generate magic number
print('Hello, what is your name?')
my_name = input()
print('Greetings, ' + my_name + '. Would you like to find out your lucky number?')
print('If yes, please tell me the day in which you were born. Use numbers only!')
b_day = input()
print('Now tell me the month in which you were born.')
b_month = input()
print('And, of course, the year.')
b_year=input() 
print('Excellent! Your lucky number is')
n = (b_day + b_month + b_year)
digits = (int(x) for x in str(n))
print(sum(digits))
print('Enjoy your newfound occult powers by taking full advantage of this number.')
